[package]
name = "MatSci"
version = "0.1.0"
edition = "2024"

[dependencies]
#see you someday
jlrs = { version = "0.19", features = ["async", "tokio-rt"] }
tokio = { version = "1", features = ["full"] }
